app/__init__.py
import os, json , smtplib
from email.mime.text import MIMEText
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from flask import Flask, render_template, redirect, url_for, flash, request, abort
from flask_bootstrap import Bootstrap
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, login_user, current_user, login_required, logout_user,UserMixin
from .admin.routes import admin
from data.data import *

app = Flask(__name__)
app.register_blueprint(admin)

app.config["SECRET_KEY"] = '123'
app.config["E-Mail"] = "noureddinezf09@gmail.com"
app.config["GMAIL_APP_PASSWORD"] = os.environ.get("token")

Bootstrap(app)
login_manager = LoginManager(app)
login_manager.init_app(app)
render = False
class User(UserMixin):
    def __init__(self, user_id, name ,email, password , admin):
        self.id = user_id
        self.email = email
        self.name = name
        self.password = password
        self.admin = admin

#This function for sending email when the purchase is made
def send_email(subject, body, to_email, from_email, app_password):
    message = MIMEMultipart()
    message["From"] = from_email
    message["To"] = to_email
    message["Subject"] = subject

    message.attach(MIMEText(body, "plain"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(from_email, app_password)
        server.sendmail(from_email, to_email, message.as_string())

@app.context_processor
def inject_now():
	""" sends datetime to templates as 'now' """
	return {'now': datetime.utcnow()}

@login_manager.user_loader
def load_user(user_id):
	user = get_user_by_id(user_id)
	try:
		return User(user[0],user[1],user[2],user[3],user[4])
	except Exception as ex:
		return str(ex) # Quand on le cree pour la premiere fois , user is None

@app.route("/")
def home():
	items = get_all_items()
	return render_template("home.html", items=items,render=True)

@app.route("/login", methods=['POST', 'GET'])
def login():
	if isinstance(current_user,str):
		pass
	elif current_user.is_authenticated:
		return redirect(url_for('home'))
	if request.method  == 'POST':
		email = request.form.get('mail')
		password = request.form.get('password')
		user = get_user_by_email(email)
		try:
			user = User(user[0],user[1],user[2],user[3],user[4])
			if check_password_hash(user.password, password):
				login_user(user)
				return redirect(url_for('login'))
			else:
				flash("Email and password incorrect!!", "error")
				return redirect(url_for('login'))
		except:
			flash("please check your credentials", "error")
			return redirect(url_for('login'))
	return render_template("login.html")

@app.route("/register", methods=['POST', 'GET'])
def register():
	if isinstance(current_user,str):
		pass
	elif current_user.is_authenticated:
		return redirect(url_for('home'))
	if request.method  == 'POST':
		name = request.form.get('name')
		email = request.form.get('mail')
		password = request.form.get('password')
		user = get_user_by_email(email)
		if user:
			flash(f"User with email {user[2]} already exists!!<br> <a href={url_for('login')}>Login now!</a>", "error")
			return redirect(url_for('register'))

		new_user = register_user(name=name,
						email=email,
						password=generate_password_hash(
									password,
									method='pbkdf2:sha256',
									salt_length=8))
		flash('Thanks for registering! You may login now.', f'success')

		return redirect(url_for('login'))
	return render_template("register.html")

@app.route("/logout")
@login_required
def logout():
	logout_user()
	return redirect(url_for('login'))


@app.route("/add/<id>", methods=['POST'])
@login_required
def add_to_cart(id):
	if not current_user.is_authenticated:
		flash(f'You must login first!<br> <a href={url_for("login")}>Login now!</a>', 'error')
		return redirect(url_for('login'))

	item = get_item_by_id(id)
	if request.method == "POST":
		quantity = request.form["quantity"]
		add_to_cart_db(current_user.id, id, quantity)
		flash(f'''{item[1]} successfully added to the <a href=cart>cart</a>.<br> <a href={url_for("cart")}>view cart!</a>''','success')
		return redirect(url_for('home'))

@app.route("/cart")
@login_required
def cart():
	price=0
	price_ids = []
	quantity = []
	user_items = get_user_items(current_user.id)
	for cart in user_items:
		quantity.append(cart[3])
		price_id_dict = {
			"price": cart[4],
			"quantity": cart[3],
			}
		price_ids.append(price_id_dict)
		price += cart[3]*cart[2]
	return render_template('cart.html',  items = user_items , price=price, price_ids=price_ids, quantity=quantity)


@app.route("/remove/<id>/<quantity>")
@login_required
def remove(id, quantity):
	remove_from_cart_by_id(id)
	return redirect(url_for('cart'))

@app.route('/item/<int:id>')
def item(id):
	item = get_item_by_id(id)
	return render_template('item.html', item=item)


@app.route('/search')
def search():
	query = request.args['query']
	query = f"%{query}%"
	items = search_in_items(query)
	return render_template('home.html', items=items, search=True, query=query[1:][:-1])

@app.route('/payment_success')
def payment_success():
	return render_template('success.html')

@app.route('/payment_failure')
def payment_failure():
	return render_template('failure.html')

@app.route('/pay', methods=['POST','GET'])
def pay():
	ordered_items = get_all_cart_items(current_user.id)
	if request.method =='POST':
		for item in ordered_items:
			remove_from_cart_by_id(item[0])
			to_email = current_user.email
			subject = "Payment"
			Body = "Your payment was successfully made , hope you like our services"
			send_email(subject , Body, to_email,app.config["E-Mail"],app.config["GMAIL_APP_PASSWORD"])
		return redirect(url_for('payment_success'))
	return render_template('pay.html')

app/admin/routes.py
from flask import Blueprint, render_template, url_for, flash,request
from werkzeug.utils import redirect
from ..funcs import admin_only
from data.data import *


admin = Blueprint("admin", __name__, url_prefix="/admin", static_folder="static", template_folder="templates")

@admin.route('/items')
@admin_only
def items():
    items = get_all_items()
    return render_template("admin/items.html", items=items)

@admin.route('/')
@admin_only
def dashboard():
    return redirect(url_for('admin.items'))

@admin.route('/add', methods=['POST', 'GET'])
@admin_only
def add():
    if request.method  == 'POST':
        name = request.form.get('name')
        price = request.form.get('price')
        category = request.form.get('category')
        details = request.form.get('details')
        img_file = request.files['image']
        img_filename = img_file.filename
        img_file.save('app/static/uploads/' + img_filename)
        image = url_for('static', filename=f'uploads/{img_filename}')
        price_id = request.form.get('price_id')
        insert_item(name , price , category , image , details , price_id)
        flash(f'{name} added successfully!','success')
        return redirect(url_for('admin.items'))
    return render_template("admin/add.html",item={})

@admin.route('/edit/<int:id>', methods=['POST', 'GET'])
@admin_only
def edit(id):
    item = get_item_by_id(id)
    if request.method  == 'POST':
            name = request.form.get('name')
            price = request.form.get('price')
            category = request.form.get('category')
            details = request.form.get('details')
            price_id = request.form.get('price_id')
            img_file = request.files['image']
            img_filename = img_file.filename
            img_file.save('app/static/uploads/' + img_filename)
            image = url_for('static', filename=f'uploads/{img_filename}')
            update_item_by_id(id,name,price,category,image ,details,price_id)
            return redirect(url_for('admin.items'))
    return render_template("admin/add.html",item=item , edit=True)

@admin.route('/delete/<int:id>')
@admin_only
def delete(id):
    item = get_item_by_id(id)
    delete_item_by_id(id)
    flash(f'{item[1]} deleted successfully', 'error')
    return redirect(url_for('admin.items'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Serif:400,italic|Droid+Sans:400,Brush+Script:400,Cursive:400,Righteous:400,Carme:400,Julius+Sans+One:400">
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('home') }}">Shop</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0 ml-auto" action="{{ url_for('search') }}">
          <input class="form-control mr-sm-2" type="search" name="query" placeholder="Search" size="40" required>
          <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">
        </form>
        <ul class="navbar-nav ml-auto">
          {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('home') }}">Home</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('register') }}">Register</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class='fa fa-bell' style='font-size:24px'></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('cart') }}">
                <i class="fa fa-shopping-cart" style="font-size:25px"></i>
              </a>
            </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class='fa fa-user-circle' style='font-size:25px'></i>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <span class="nav-link text-muted">{{ current_user.name }}</a>
              <div class="dropdown-divider"></div>
              <a class="nav-link" href="{{ url_for('home') }}">home</a>
              {% if current_user.admin == 1 %}
              <a class="nav-link" href="{{ url_for('admin.dashboard') }}">Admin</a>
              {% endif %}
              <a class="nav-link" href="{{ url_for('logout') }}"><font color="red">Logout</font></a>
            </div>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>      
    {% if render %}
        <div class="img-slider">
          <img src="../static/uploads/pexels-lalesh-aldarwish-194511.jpg" alt="" class="img">
          <img src="../static/uploads/pexels-max-deroin-51415.jpg" alt="" class="img">
          <img src="../static/uploads/pexels-lucie-liz-3165335.jpg" alt="" class="img">
          <img src="../static/uploads/pexels-tyler-lastovich-699122.jpg" alt="" class="img">
          <img src="../static/uploads/pexels-pixabay-275033.jpg" alt="" class="img">
          <img src="../static/uploads/pexels-soumil-kumar-735911.jpg" alt="" class="img">
          <img src="../static/uploads/pexels-pixabay-257923.jpg" alt="" class="img">       
    </div>
      {% endif %}
    <div class="container">
      <div class="main">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    <script type="text/javascript" src="{{ url_for('static', filename='script.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z"/></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z"/></symbol><symbol id="mail" viewBox="0 0 24 24">
  <path d="M21 4H3C1.89543 4 1 4.89543 1 6V18C1 19.1046 1.89543 20 3 20H21C22.1046 20 23 19.1046 23 18V6C23 4.89543 22.1046 4 21 4ZM21 6L12 13L3 6H21ZM3 18V8.618L12 15.618L21 8.618V18H3Z" />
</symbol>
</svg>
  </body>
    <footer >
    <div class="footer0">
      <h1>Shop</h1>
    </div>
    <div class="footer1 ">
      Connect with us at<div class="social-media">
        <a href="#">
          <ion-icon name="logo-facebook"></ion-icon>
        </a>
        <a href="#">
          <ion-icon name="logo-linkedin"></ion-icon>
        </a>
        <a href="#">
          <ion-icon name="logo-youtube"></ion-icon>
        </a>
        <a href="#">
          <ion-icon name="logo-instagram"></ion-icon>
        </a>
        <a href="#">
          <ion-icon name="logo-twitter"></ion-icon>
        </a>
      </div>
    </div>
    <div class="footer2">
      <div class="product">
        <div class="heading">Products</div>
        <div class="div">Sell your Products</div>
        <div class="div">Advertise</div>
        <div class="div">Pricing</div>
        <div class="div">Product Buisness</div>

      </div>
      <div class="services">
        <div class="heading">Services</div>
        <div class="div">Return</div>
        <div class="div">Cash Back</div>
        <div class="div">Affiliate Marketing</div>
        <div class="div">Others</div>
      </div>
      <div class="Company">
        <div class="heading">Company</div>
        <div class="div">Complaint</div>
        <div class="div">Careers</div>
        <div class="div">Affiliate Marketing</div>
        <div class="div">Support</div>
      </div>
      <div class="Get Help">
        <div class="heading">Get Help</div>
        <div class="div">Help Center</div>
        <div class="div">Privacy Policy</div>
        <div class="div">Terms</div>
      </div>
    </div>
    <div class="footer3">Copyright © <h4>Shop</h4> 2022-2023</div>
    </footer>
</html>

app/templates/cart.html
{% extends "base.html" %}

{% block title %}
	Cart - Shop
{% endblock %}
<script src="https://js.stripe.com/v3/"></script>
{% block content %}
	{% with msgs =  get_flashed_messages(with_categories=True) %}
	{% for c, msg in msgs %}
		{% if c == 'error' %}
			<div class="flash-error">
		{% else %}
			<div class="success">
		{% endif %}
			{{ msg | safe }}</div><br>
	{% endfor %}
	{% endwith %}

	{% if not items %}
		<div class="flash-error">
			Cart is empty!<br>
			<a href="{{ url_for('home') }}">Discover new items</a>
		</div>
	{% else %}
		<a href="{{ url_for('home') }}" class="right-item">Add more items</a><br><br>
	{% endif %}

	<div class="items">
	{% for i in range(items|length) %}
    <div class="item">
		<div class="item-wrapper">
			<div class="img-wrapper">
				<img src="{{ items[i][5] }}" class="pic">
			</div>
			<b>{{ items[i][1] }}</b>
			<span class="right-item"></span><br>
			Quantity: 
			<span class="right-item">{{ quantity[i] }}</span><br>
			Total:
			<span class="right-item">{{ quantity[i]*items[i][2] }} MAD</span>
			<br><br>
			<a href="{{ url_for('remove', id=items[i][0], quantity=quantity[i]) }}">
				<button class="remove-from-cart"> Remove from Cart </button>
			</a>
		</div>
	</div>
        {% endfor %}
	</div>
	{% if price %}
	<div class="pay">
		<form method="GET" action="{{ url_for('pay') }}">
			<input type="hidden" value="{{ price_ids }}" name="price_ids">
			Total: {{ price }} MAD<br><br>
			<button class="bg-success btn-block btn-primary checkout"> Pay </button>
		</form>
	</div>
	{% endif %}
{% endblock %}

app/templates/failure.html
{% extends "base.html" %}

{% block title %}
	Payment Failure - Shop
{% endblock %}

{% block content %}
    <div class="flash-error">
        Payment couldn't be completed. Please try again.
        <a href="{{ url_for('cart') }}">Go back!</a>
    </div>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block title %}
	Home - Shop
{% endblock %}
      
{% block content %}
	{% if search %}
	<h3>Search results for "{{ query }}":</h3>
	{% endif %}
</div>

	{% with msgs =  get_flashed_messages(with_categories=True) %}
	{% for c, msg in msgs %}
		{% if c == 'error' %}
			<div class="flash-error">
		{% else %}
			<div class="success">
		{% endif %}
			{{ msg | safe}}</div><br>
	{% endfor %}
	{% endwith %}
	</div>
	<h3>Best Offer</h3>
	<br>
		<div class="container2">
		<div class="Best-items">
			
	{% for item in items[0:4] %}<!--Les trois articles premières dans la base donnes sont les meilleure offre.-->
	<a href="{{ url_for('item', id=item[0]) }}" class='item-link'>
		<div class="item">
			<div class="item-wrapper">
				<div class="img-wrapper">
					<img src="{{ item[4] }}" class="pic">
				</div>
				<span class="left-item">{{ item[1] }}</span>
				<span class="right-item">{{ item[2] }} MAD</span><br>
					
			</div>
		</div>
	</a>
	{% endfor %}
	</div>

	<br><br><h3>All</h3>
	<br>
	<div class="All-items">
	{% for item in items[::-1] %}
	<a href="{{ url_for('item', id=item[0]) }}">
		<div class="item">
			<div class="item-wrapper">
				<div class="img-wrapper">
					<img src="{{ item[4] }}" class="pic">
				</div>
				<span class="left-item">{{ item[1] }}</span>
				<span class="right-item"><p>${{ item[2] }}</p></span><br>					
			</div>
		</div>
	</a>
	{% endfor %}
	</div>

	{% if not items %}
	<div class="flash-error">
		No items found.<br>
		<a href="{{ url_for('home') }}">Discover new items</a>
	</div>
</div>
</div>
</div>

</div>
	{% endif %}
{% endblock %}

app/templates/item.html
{% extends "base.html" %}

{% block title %}
	{{ item.name }} - Shop
{% endblock %}

{% block content %}
	{% with msgs =  get_flashed_messages(with_categories=True) %}
	{% for c, msg in msgs %}
		{% if c == 'error' %}
			<div class="flash-error">
		{% else %}
			<div class="success">
		{% endif %}
			{{ msg | safe}}</div><br>
	{% endfor %}
	{% endwith %}

			<div class="item-display">
				<div class="img-wrapper">
					<img src="{{ item[4] }}" class="pic">
				</div>
				<b>{{ item[1] }}</b>
				<span class="right-item">{{ item[2] }} MAD</span><br>
                <div class="details"><p>{{ item[5] | safe }}</p></div>
				<form action="{{ url_for('add_to_cart', id=item[0]) }}" method="POST">
                    Quantity: 
                    <input type="number" value="1" name="quantity" min="1" max="50" onkeyup="if(this.value > 50) this.value=50;" required>
                    <br><br>
					<input type="submit" class="add-to-cart" value="Add to Cart" name="add">
                </form>
				</a>
			</div>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}
	Login - Shop
{% endblock %}

{% block content %}
	<hr>
	{% with msgs =  get_flashed_messages(with_categories=True) %}
		{% for c, msg in msgs %}
			{% if c == 'error' %}
				<div class="flash-error">
			{% else %}
				<div class="success">
			{% endif %}
				{{ msg | safe }}</div><br>
		{% endfor %}
	{% endwith %}
	<div class="user-modal-container">
			<ul class="switcher">
				<li><a class="selected" href="/login">Log in</a></li>
				<li><a href="/register">New account</a></li>
			</ul>
			<div id="login" class="is-selected">
				<form class="form" action="/login" method="POST" >
					<p class="fieldset">
						<label class="image-replace email" for="signin-email">E-mail</label>
						<input class="full-width has-padding has-border" id="signin-email" type="email" name="mail" placeholder="E-mail" required>
					</p>
					<p class="fieldset">
						<label class="image-replace password" for="signin-password">Password</label>
						<input class="full-width has-padding has-border" id="signin-password" type="password" name="password" placeholder="Password" required>
					</p>
					
					<p class="fieldset">
						<input class="full-width" type="submit" value="Log in">
					</p>
				</form>
			</div>


    </form>
  </div>
	</div>
{% endblock %}

app/templates/pay.html
{% extends "base.html" %}

{% block title %}
	Pay - Shop
{% endblock %}

{% block content %}
	<hr>
	{% with msgs =  get_flashed_messages(with_categories=True) %}
		{% for c, msg in msgs %}
			{% if c == 'error' %}
				<div class="flash-error">
			{% else %}
				<div class="success">
			{% endif %}
				{{ msg | safe }}</div><br>
		{% endfor %}
	{% endwith %}
	<div id="Pay" class="Pay">
				<form class="form" action="/pay" method="POST" >
					<b>Enter your information</b>
					<p class="fieldset">
						<input class="full-width has-padding has-border" id="name" name="name" placeholder="Your Name" required>
					</p>
					<p class="fieldset">
						<input class="full-width has-padding has-border" id="account_number" type="text" name="account_number" placeholder="Your Account Number" required>
					</p>
					<p class="fieldset">
						<input class="full-width has-padding has-border" id="birthday" name="birthday" type="date" required>
					</p>
					<p class="fieldset">
						<input class="full-width has-padding has-border" type="text" name="cvv" pattern="[0-9]{3,4}" title="Enter a valid CVV" placeholder="Your cvv" required>
					</p>
					<p class="fieldset">
						<input class="full-width has-padding has-border" id="country" type="text" name="country" placeholder="your country" required>
					</p>
					<p class="fieldset">
						<input class="full-width has-padding has-border" name="city" placeholder="Your city" required>
					</p>
					<p class="fieldset">
						<input class="full-width has-padding has-border" name="address" placeholder="Your address" required>
					</p>
					<p class="fieldset">
						<input class="full-width has-padding has-border" type="text" name="Postal_code" pattern="^[0-9]{5,6}$" placeholder="Enter a valid postal code" required>
					</p>
					<p class="fieldset">
						<input class="full-width" type="submit" value="Submit">
					</p>
				</form>
	</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}
	Register - Shop
{% endblock %}

{% block content %}
	<hr>
	{% with msgs =  get_flashed_messages(with_categories=True) %}
		{% for c, msg in msgs %}
			{% if c == 'error' %}
				<div class="flash-error">
			{% else %}
				<div class="success">
			{% endif %}
				{{ msg | safe }}</div><br>
		{% endfor %}
	{% endwith %}
		<div class="user-modal-container">
			<ul class="switcher">
				<li><a  href="/login">Sign in</a></li>
				<li><a class="selected" 	href="/register">New account</a></li>
			</ul>
			<div id="signup" class="is-selected">
				<form class="form" action="/register" method="POST" >
					<p class="fieldset">
						<label class="image-replace username" for="signup-username">Username</label>
						<input class="full-width has-padding has-border" id="signup-username" type="text" name="name" placeholder="name" required>
					</p>

					<p class="fieldset">
						<label class="image-replace email" for="signup-email">E-mail</label>
						<input class="full-width has-padding has-border" id="signup-email" type="email" name="mail" placeholder="E-mail" required>
					</p>

					<p class="fieldset">
						<label class="image-replace password" for="signup-password">Password</label>
						<input class="full-width has-padding has-border" id="signup-password" type="password" name="password" placeholder="Password" required>
					</p>

					<p class="fieldset">
						<label class="image-replace password" for="signup-password">Password</label>
						<input class="full-width has-padding has-border" id="signup-password" type="password" name="confirm_password" placeholder="Confirm Password" required>
					</p>

					<p class="fieldset">
						<input class="full-width has-padding" type="submit" value="Create account">
					</p>
				</form>
			</div>
	</div>
{% endblock %}

app/templates/success.html
{% extends "base.html" %}

{% block title %}
	Payment Success - Shop
{% endblock %}

{% block content %}
    <div class="success">
        Payment successful!!<br>
        Order placed successfully.
        <a href="{{ url_for('home') }}">View items</a>
    </div>
{% endblock %}